[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.10.31"

# Description
title = "CRL Tasks"
description="Constrained RL task suite and configuration package."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}

[core]
reloadable = false

[[python.module]]
name = "crl_tasks"
